{{/*
Copyright 2017 The Openstack-Helm Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/}}

{{- if .Values.manifests_enabled.ceph_exporter }}
{{- $envAll := . }}
{{- $dependencies := .Values.dependencies.ceph_exporter }}
{{- $mounts_ceph_exporter := .Values.pod.mounts.ceph_exporter.ceph_exporter }}
{{- $mounts_ceph_exporter_init := .Values.pod.mounts.ceph_exporter.init_container }}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ceph-exporter
spec:
  replicas: {{ .Values.pod.replicas.ceph_exporter }}
{{ tuple $envAll | include "helm-toolkit.snippets.kubernetes_upgrades_deployment" | indent 2 }}
  template:
    metadata:
      labels:
        app: ceph-exporter
      name: ceph-exporter
    spec:
      nodeSelector:
        {{ .Values.labels.ceph_exporter.node_selector_key }}: {{ .Values.labels.ceph_exporter.node_selector_value }}
      terminationGracePeriodSeconds: {{ .Values.pod.lifecycle.termination_grace_period.timeout | default "30" }}
      initContainers:
{{ tuple $envAll $dependencies $mounts_ceph_exporter_init | include "helm-toolkit.snippets.kubernetes_entrypoint_init_container" | indent 8 }}
      containers:
        - name: cephexporter
          image: {{ .Values.images.ceph_exporter }}
          imagePullPolicy: {{ .Values.images.pull_policy }}
{{ tuple $envAll $envAll.Values.pod.resources.ceph_exporter | include "helm-toolkit.snippets.kubernetes_resources" | indent 10 }}
          ports:
            - name: c-exporter
              containerPort: {{ .Values.network.ceph_exporter.port }}
          volumeMounts:
          - name: pod-etc-exporter
            mountPath: /etc/ceph
          - name: ceph-etc
            mountPath: /etc/ceph/ceph.conf
            subPath: ceph.conf
            readOnly: true
          - name: ceph-client-admin-keyring
            mountPath: /etc/ceph/ceph.client.admin.keyring
            subPath: ceph.client.admin.keyring
            readOnly: true
{{ if $mounts_ceph_exporter.volumeMounts }}{{ toYaml $mounts_ceph_exporter.volumeMounts | indent 10 }}{{ end }}
      volumes:
      - name: pod-etc-exporter
        emptyDir: {}
      - name: ceph-etc
        configMap:
          name: ceph-etc
      - name: ceph-client-admin-keyring
        secret:
          secretName: {{ .Values.secrets.keyrings.admin }}
{{ if $mounts_ceph_exporter.volumes }}{{ toYaml $mounts_ceph_exporter.volumes | indent 6 }}{{ end }}
{{- end }}
