apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-logging
  labels:
    component: elasticsearch
    role: client
spec:
  type: LoadBalancer
  selector:
    k8s-app: elasticsearch-logging
    component: elasticsearch
    role: client
  ports:
  - name: {{ .Values.network.client.name }}
    port: {{ .Values.network.client.port }}
    protocol: {{ .Values.network.client.proto }}
